//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDKT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TD_DVKT
    {
        public TD_DVKT()
        {
            this.CUOC_KT = new HashSet<CUOC_KT>();
            this.AspNetUsers = new HashSet<AspNetUser>();
        }

        [Required(ErrorMessage = "Nhập mã đơn vị")]
        [Display(Name = "Mã đơn vị")]
        public string MA { get; set; }

        [Required(ErrorMessage = "Nhập tên đơn vị")]
        [Display(Name = "Tên đơn vị")]
        public string TEN { get; set; }

        [Display(Name = "Trạng thái")]
        public bool CanAudit { get; set; }

        [Display(Name = "Ngày thành lập")]
        public Nullable<System.DateTime> BeginDate { get; set; }

        [Display(Name = "Ngày dừng hoạt động")]
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual ICollection<CUOC_KT> CUOC_KT { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
    }
}
