//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDKT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TD_LVKT
    {
        public TD_LVKT()
        {
            this.CUOC_KT = new HashSet<CUOC_KT>();
        }

        [Required(ErrorMessage = "Nhập mã lĩnh vực kiểm toán")]
        [Display(Name = "Mã")]
        public string MA { get; set; }

        [Required(ErrorMessage = "Nhập tên lĩnh vực kiểm toán")]
        [Display(Name = "Lĩnh vực")]
        public string TEN { get; set; }
    
        public virtual ICollection<CUOC_KT> CUOC_KT { get; set; }
    }
}
