//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDKT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TDKTEntities : DbContext
    {
        public TDKTEntities()
            : base("name=TDKTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CUOC_KT> CUOC_KT { get; set; }
        public virtual DbSet<TD_DVKT> TD_DVKT { get; set; }
        public virtual DbSet<TD_LHKT> TD_LHKT { get; set; }
        public virtual DbSet<TD_LVKT> TD_LVKT { get; set; }
    
        public virtual ObjectResult<getCuoc_Result> getCuoc(string namkt, string donvi)
        {
            var namktParameter = namkt != null ?
                new ObjectParameter("namkt", namkt) :
                new ObjectParameter("namkt", typeof(string));
    
            var donviParameter = donvi != null ?
                new ObjectParameter("donvi", donvi) :
                new ObjectParameter("donvi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getCuoc_Result>("getCuoc", namktParameter, donviParameter);
        }
    
        public virtual ObjectResult<getUsers_Result> getUsers(string donvi)
        {
            var donviParameter = donvi != null ?
                new ObjectParameter("donvi", donvi) :
                new ObjectParameter("donvi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getUsers_Result>("getUsers", donviParameter);
        }
    }
}
