//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THKQKT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUOC_KT
    {
        public int ID { get; set; }
        public string MA_CUOC { get; set; }
        public string TEN_CUOC { get; set; }
        public string NAM_KT { get; set; }
        public string GHI_CHU { get; set; }
        public string MA_DVKT { get; set; }
        public string MA_LVKT { get; set; }
        public string MA_LHKT { get; set; }
        public bool KTTX { get; set; }
        public string NIEN_DO { get; set; }
        public string TOM_TAT { get; set; }
        public bool TRINH_KH { get; set; }
        public Nullable<System.DateTime> NGAY_TRINH_KH { get; set; }
        public bool DUYET_KH { get; set; }
        public Nullable<System.DateTime> NGAY_DUYET_KH { get; set; }
        public Nullable<bool> QUYET_DINH_KT { get; set; }
        public string SO_QD { get; set; }
        public Nullable<System.DateTime> NGAY_QD { get; set; }
        public Nullable<short> SO_NGAY_KT { get; set; }
        public Nullable<System.DateTime> NGAY_BDQD { get; set; }
        public Nullable<System.DateTime> NGAY_BDTT { get; set; }
        public bool BAT_DAU_KT { get; set; }
        public Nullable<System.DateTime> NGAY_KTKH { get; set; }
        public bool KET_THUC_KT { get; set; }
        public Nullable<System.DateTime> NGAY_KTTT { get; set; }
        public bool TRINH_DUYET_BCKT { get; set; }
        public Nullable<System.DateTime> NGAY_TRINH_DUYET_BCKT { get; set; }
        public bool DUYET_BCKT { get; set; }
        public Nullable<System.DateTime> NGAY_DUYET_BCKT { get; set; }
        public bool TRINH_PHBC_DV { get; set; }
        public Nullable<System.DateTime> NGAY_TRINH_PHBC_DV { get; set; }
        public bool TRINH_PHBC_VTH { get; set; }
        public Nullable<System.DateTime> NGAY_TRINH_PHBC_VTH { get; set; }
        public bool PH_BCKT { get; set; }
        public Nullable<System.DateTime> NGAY_PHBCKT { get; set; }
        public Nullable<bool> Bookmarked { get; set; }
    
        public virtual TD_DVKT TD_DVKT { get; set; }
        public virtual TD_LHKT TD_LHKT { get; set; }
        public virtual TD_LVKT TD_LVKT { get; set; }
    }
}
