//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THKQKT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mChiTieu
    {
        public mChiTieu()
        {
            this.tblChiTieuBienDongs = new HashSet<tblChiTieuBienDong>();
            this.tblSoLieuChiTieux = new HashSet<tblSoLieuChiTieu>();
        }
    
        public long MaChiTieu { get; set; }
        public Nullable<int> MaBieuMau { get; set; }
        public string KyHieu { get; set; }
        public string TenChiTieu { get; set; }
        public string GhiChu { get; set; }
    
        public virtual mBieuMau mBieuMau { get; set; }
        public virtual ICollection<tblChiTieuBienDong> tblChiTieuBienDongs { get; set; }
        public virtual ICollection<tblSoLieuChiTieu> tblSoLieuChiTieux { get; set; }
    }
}
