//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THKQKT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSoLieuChiTieu
    {
        public long MaSoLieuChiTieu { get; set; }
        public Nullable<long> MaChiTieu { get; set; }
        public Nullable<int> MaCuoc { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public string NoiDung { get; set; }
        public Nullable<decimal> SoTien { get; set; }
        public string UserIDKhoiTao { get; set; }
        public Nullable<System.DateTime> ThoiGianKhoiTao { get; set; }
        public string UserIDChinhSua { get; set; }
        public Nullable<System.DateTime> ThoiGianChinhSua { get; set; }
        public string GhiChu { get; set; }
    
        public virtual mChiTieu mChiTieu { get; set; }
    }
}
