//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THKQKT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_DVKT
    {
        public TD_DVKT()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
            this.CUOC_KT = new HashSet<CUOC_KT>();
        }
    
        public string MA { get; set; }
        public string TEN { get; set; }
        public bool CanAudit { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        public virtual ICollection<CUOC_KT> CUOC_KT { get; set; }
    }
}
