//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THKQKT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class THKQKTEntities : DbContext
    {
        public THKQKTEntities()
            : base("name=THKQKTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<mBieuMau> mBieuMaus { get; set; }
        public virtual DbSet<mChiTieu> mChiTieux { get; set; }
        public virtual DbSet<tblChiTieuBienDong> tblChiTieuBienDongs { get; set; }
        public virtual DbSet<tblSoLieuChiTieu> tblSoLieuChiTieux { get; set; }
    
        [DbFunction("THKQKTEntities", "GetAllChiTieuActive")]
        public virtual IQueryable<GetAllChiTieuActive_Result> GetAllChiTieuActive(Nullable<long> maMauBieu, Nullable<System.DateTime> ngayThucHien)
        {
            var maMauBieuParameter = maMauBieu.HasValue ?
                new ObjectParameter("MaMauBieu", maMauBieu) :
                new ObjectParameter("MaMauBieu", typeof(long));
    
            var ngayThucHienParameter = ngayThucHien.HasValue ?
                new ObjectParameter("NgayThucHien", ngayThucHien) :
                new ObjectParameter("NgayThucHien", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetAllChiTieuActive_Result>("[THKQKTEntities].[GetAllChiTieuActive](@MaMauBieu, @NgayThucHien)", maMauBieuParameter, ngayThucHienParameter);
        }
    
        [DbFunction("THKQKTEntities", "GetAllStatus")]
        public virtual IQueryable<GetAllStatus_Result> GetAllStatus()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetAllStatus_Result>("[THKQKTEntities].[GetAllStatus]()");
        }
    
        [DbFunction("THKQKTEntities", "GetAllStatusByDV")]
        public virtual IQueryable<GetAllStatusByDV_Result> GetAllStatusByDV(Nullable<bool> isFilterDV, string madonvi, string namkt)
        {
            var isFilterDVParameter = isFilterDV.HasValue ?
                new ObjectParameter("isFilterDV", isFilterDV) :
                new ObjectParameter("isFilterDV", typeof(bool));
    
            var madonviParameter = madonvi != null ?
                new ObjectParameter("madonvi", madonvi) :
                new ObjectParameter("madonvi", typeof(string));
    
            var namktParameter = namkt != null ?
                new ObjectParameter("namkt", namkt) :
                new ObjectParameter("namkt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetAllStatusByDV_Result>("[THKQKTEntities].[GetAllStatusByDV](@isFilterDV, @madonvi, @namkt)", isFilterDVParameter, madonviParameter, namktParameter);
        }
    
        public virtual ObjectResult<getDonVi_Result> getDonVi(Nullable<bool> canAudit, string namkt)
        {
            var canAuditParameter = canAudit.HasValue ?
                new ObjectParameter("canAudit", canAudit) :
                new ObjectParameter("canAudit", typeof(bool));
    
            var namktParameter = namkt != null ?
                new ObjectParameter("namkt", namkt) :
                new ObjectParameter("namkt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getDonVi_Result>("getDonVi", canAuditParameter, namktParameter);
        }
    
        public virtual ObjectResult<getDonViDo_Result> getDonViDo(string namkt)
        {
            var namktParameter = namkt != null ?
                new ObjectParameter("namkt", namkt) :
                new ObjectParameter("namkt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getDonViDo_Result>("getDonViDo", namktParameter);
        }
    
        public virtual ObjectResult<getLinhVuc_Result> getLinhVuc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getLinhVuc_Result>("getLinhVuc");
        }
    
        public virtual ObjectResult<getLoaiHinh_Result> getLoaiHinh()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getLoaiHinh_Result>("getLoaiHinh");
        }
    
        public virtual ObjectResult<string> getMaDonvi(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("getMaDonvi", usernameParameter);
        }
    
        public virtual ObjectResult<GetNewCuocStatus_Result> GetNewCuocStatus(string namkt, Nullable<System.DateTime> ngaylapbc, string cat, string madonvi)
        {
            var namktParameter = namkt != null ?
                new ObjectParameter("namkt", namkt) :
                new ObjectParameter("namkt", typeof(string));
    
            var ngaylapbcParameter = ngaylapbc.HasValue ?
                new ObjectParameter("ngaylapbc", ngaylapbc) :
                new ObjectParameter("ngaylapbc", typeof(System.DateTime));
    
            var catParameter = cat != null ?
                new ObjectParameter("cat", cat) :
                new ObjectParameter("cat", typeof(string));
    
            var madonviParameter = madonvi != null ?
                new ObjectParameter("madonvi", madonvi) :
                new ObjectParameter("madonvi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetNewCuocStatus_Result>("GetNewCuocStatus", namktParameter, ngaylapbcParameter, catParameter, madonviParameter);
        }
    
        public virtual ObjectResult<getPhatHanh_Result> getPhatHanh(string namkt, Nullable<System.DateTime> ngaylapbc, string donvi)
        {
            var namktParameter = namkt != null ?
                new ObjectParameter("namkt", namkt) :
                new ObjectParameter("namkt", typeof(string));
    
            var ngaylapbcParameter = ngaylapbc.HasValue ?
                new ObjectParameter("ngaylapbc", ngaylapbc) :
                new ObjectParameter("ngaylapbc", typeof(System.DateTime));
    
            var donviParameter = donvi != null ?
                new ObjectParameter("donvi", donvi) :
                new ObjectParameter("donvi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getPhatHanh_Result>("getPhatHanh", namktParameter, ngaylapbcParameter, donviParameter);
        }
    
        public virtual ObjectResult<getRoles_Result> getRoles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getRoles_Result>("getRoles");
        }
    
        public virtual ObjectResult<getUsers_Result> getUsers(string donvi)
        {
            var donviParameter = donvi != null ?
                new ObjectParameter("donvi", donvi) :
                new ObjectParameter("donvi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getUsers_Result>("getUsers", donviParameter);
        }
    
        public virtual ObjectResult<string> getYear()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("getYear");
        }
    
        public virtual ObjectResult<getYears_Result> getYears()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getYears_Result>("getYears");
        }
    
        public virtual int sp_mBieuMau_DeleteByField(string fieldName, string value)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_mBieuMau_DeleteByField", fieldNameParameter, valueParameter);
        }
    
        public virtual int sp_mBieuMau_DeleteByPrimaryKey(Nullable<int> maBieuMau)
        {
            var maBieuMauParameter = maBieuMau.HasValue ?
                new ObjectParameter("MaBieuMau", maBieuMau) :
                new ObjectParameter("MaBieuMau", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_mBieuMau_DeleteByPrimaryKey", maBieuMauParameter);
        }
    
        public virtual int sp_mBieuMau_Insert(ObjectParameter maBieuMau, string kyHieu, string tenBieuMau, string ghiChu)
        {
            var kyHieuParameter = kyHieu != null ?
                new ObjectParameter("KyHieu", kyHieu) :
                new ObjectParameter("KyHieu", typeof(string));
    
            var tenBieuMauParameter = tenBieuMau != null ?
                new ObjectParameter("TenBieuMau", tenBieuMau) :
                new ObjectParameter("TenBieuMau", typeof(string));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_mBieuMau_Insert", maBieuMau, kyHieuParameter, tenBieuMauParameter, ghiChuParameter);
        }
    
        public virtual ObjectResult<sp_mBieuMau_SelectAll_Result> sp_mBieuMau_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mBieuMau_SelectAll_Result>("sp_mBieuMau_SelectAll");
        }
    
        public virtual int sp_mBieuMau_SelectByField(string fieldName, string value)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_mBieuMau_SelectByField", fieldNameParameter, valueParameter);
        }
    
        public virtual ObjectResult<sp_mBieuMau_SelectByPrimaryKey_Result> sp_mBieuMau_SelectByPrimaryKey(Nullable<int> maBieuMau)
        {
            var maBieuMauParameter = maBieuMau.HasValue ?
                new ObjectParameter("MaBieuMau", maBieuMau) :
                new ObjectParameter("MaBieuMau", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mBieuMau_SelectByPrimaryKey_Result>("sp_mBieuMau_SelectByPrimaryKey", maBieuMauParameter);
        }
    
        public virtual int sp_mBieuMau_Update(Nullable<int> maBieuMau, string kyHieu, string tenBieuMau, string ghiChu)
        {
            var maBieuMauParameter = maBieuMau.HasValue ?
                new ObjectParameter("MaBieuMau", maBieuMau) :
                new ObjectParameter("MaBieuMau", typeof(int));
    
            var kyHieuParameter = kyHieu != null ?
                new ObjectParameter("KyHieu", kyHieu) :
                new ObjectParameter("KyHieu", typeof(string));
    
            var tenBieuMauParameter = tenBieuMau != null ?
                new ObjectParameter("TenBieuMau", tenBieuMau) :
                new ObjectParameter("TenBieuMau", typeof(string));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_mBieuMau_Update", maBieuMauParameter, kyHieuParameter, tenBieuMauParameter, ghiChuParameter);
        }
    
        public virtual int sp_mChiTieu_DeleteByField(string fieldName, string value)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_mChiTieu_DeleteByField", fieldNameParameter, valueParameter);
        }
    
        public virtual int sp_mChiTieu_DeleteByPrimaryKey(Nullable<long> maChiTieu)
        {
            var maChiTieuParameter = maChiTieu.HasValue ?
                new ObjectParameter("MaChiTieu", maChiTieu) :
                new ObjectParameter("MaChiTieu", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_mChiTieu_DeleteByPrimaryKey", maChiTieuParameter);
        }
    
        public virtual int sp_mChiTieu_Insert(ObjectParameter maChiTieu, Nullable<int> maBieuMau, string kyHieu, string tenChiTieu, string ghiChu)
        {
            var maBieuMauParameter = maBieuMau.HasValue ?
                new ObjectParameter("MaBieuMau", maBieuMau) :
                new ObjectParameter("MaBieuMau", typeof(int));
    
            var kyHieuParameter = kyHieu != null ?
                new ObjectParameter("KyHieu", kyHieu) :
                new ObjectParameter("KyHieu", typeof(string));
    
            var tenChiTieuParameter = tenChiTieu != null ?
                new ObjectParameter("TenChiTieu", tenChiTieu) :
                new ObjectParameter("TenChiTieu", typeof(string));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_mChiTieu_Insert", maChiTieu, maBieuMauParameter, kyHieuParameter, tenChiTieuParameter, ghiChuParameter);
        }
    
        public virtual ObjectResult<sp_mChiTieu_SelectAll_Result> sp_mChiTieu_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mChiTieu_SelectAll_Result>("sp_mChiTieu_SelectAll");
        }
    
        public virtual int sp_mChiTieu_SelectByField(string fieldName, string value)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_mChiTieu_SelectByField", fieldNameParameter, valueParameter);
        }
    
        public virtual ObjectResult<sp_mChiTieu_SelectByPrimaryKey_Result> sp_mChiTieu_SelectByPrimaryKey(Nullable<long> maChiTieu)
        {
            var maChiTieuParameter = maChiTieu.HasValue ?
                new ObjectParameter("MaChiTieu", maChiTieu) :
                new ObjectParameter("MaChiTieu", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mChiTieu_SelectByPrimaryKey_Result>("sp_mChiTieu_SelectByPrimaryKey", maChiTieuParameter);
        }
    
        public virtual int sp_mChiTieu_Update(Nullable<long> maChiTieu, Nullable<int> maBieuMau, string kyHieu, string tenChiTieu, string ghiChu)
        {
            var maChiTieuParameter = maChiTieu.HasValue ?
                new ObjectParameter("MaChiTieu", maChiTieu) :
                new ObjectParameter("MaChiTieu", typeof(long));
    
            var maBieuMauParameter = maBieuMau.HasValue ?
                new ObjectParameter("MaBieuMau", maBieuMau) :
                new ObjectParameter("MaBieuMau", typeof(int));
    
            var kyHieuParameter = kyHieu != null ?
                new ObjectParameter("KyHieu", kyHieu) :
                new ObjectParameter("KyHieu", typeof(string));
    
            var tenChiTieuParameter = tenChiTieu != null ?
                new ObjectParameter("TenChiTieu", tenChiTieu) :
                new ObjectParameter("TenChiTieu", typeof(string));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_mChiTieu_Update", maChiTieuParameter, maBieuMauParameter, kyHieuParameter, tenChiTieuParameter, ghiChuParameter);
        }
    
        public virtual int sp_tblChiTieuBienDong_DeleteByField(string fieldName, string value)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tblChiTieuBienDong_DeleteByField", fieldNameParameter, valueParameter);
        }
    
        public virtual int sp_tblChiTieuBienDong_DeleteByPrimaryKey(Nullable<long> maChiTieuBienDong)
        {
            var maChiTieuBienDongParameter = maChiTieuBienDong.HasValue ?
                new ObjectParameter("MaChiTieuBienDong", maChiTieuBienDong) :
                new ObjectParameter("MaChiTieuBienDong", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tblChiTieuBienDong_DeleteByPrimaryKey", maChiTieuBienDongParameter);
        }
    
        public virtual int sp_tblChiTieuBienDong_Insert(ObjectParameter maChiTieuBienDong, Nullable<long> maChiTieu, Nullable<long> maChiTieuCha, string kyHieuMoi, string tenChiTieuMoi, string congZon, Nullable<System.DateTime> thoiGianApDung, Nullable<System.DateTime> thoiGianHetHan, Nullable<int> thuTu, string userIDKhoiTao, Nullable<System.DateTime> thoiGianKhoiTao, string userIDChinhSua, Nullable<System.DateTime> thoiGianChinhSua, string ghiChu)
        {
            var maChiTieuParameter = maChiTieu.HasValue ?
                new ObjectParameter("MaChiTieu", maChiTieu) :
                new ObjectParameter("MaChiTieu", typeof(long));
    
            var maChiTieuChaParameter = maChiTieuCha.HasValue ?
                new ObjectParameter("MaChiTieuCha", maChiTieuCha) :
                new ObjectParameter("MaChiTieuCha", typeof(long));
    
            var kyHieuMoiParameter = kyHieuMoi != null ?
                new ObjectParameter("KyHieuMoi", kyHieuMoi) :
                new ObjectParameter("KyHieuMoi", typeof(string));
    
            var tenChiTieuMoiParameter = tenChiTieuMoi != null ?
                new ObjectParameter("TenChiTieuMoi", tenChiTieuMoi) :
                new ObjectParameter("TenChiTieuMoi", typeof(string));
    
            var congZonParameter = congZon != null ?
                new ObjectParameter("CongZon", congZon) :
                new ObjectParameter("CongZon", typeof(string));
    
            var thoiGianApDungParameter = thoiGianApDung.HasValue ?
                new ObjectParameter("ThoiGianApDung", thoiGianApDung) :
                new ObjectParameter("ThoiGianApDung", typeof(System.DateTime));
    
            var thoiGianHetHanParameter = thoiGianHetHan.HasValue ?
                new ObjectParameter("ThoiGianHetHan", thoiGianHetHan) :
                new ObjectParameter("ThoiGianHetHan", typeof(System.DateTime));
    
            var thuTuParameter = thuTu.HasValue ?
                new ObjectParameter("ThuTu", thuTu) :
                new ObjectParameter("ThuTu", typeof(int));
    
            var userIDKhoiTaoParameter = userIDKhoiTao != null ?
                new ObjectParameter("UserIDKhoiTao", userIDKhoiTao) :
                new ObjectParameter("UserIDKhoiTao", typeof(string));
    
            var thoiGianKhoiTaoParameter = thoiGianKhoiTao.HasValue ?
                new ObjectParameter("ThoiGianKhoiTao", thoiGianKhoiTao) :
                new ObjectParameter("ThoiGianKhoiTao", typeof(System.DateTime));
    
            var userIDChinhSuaParameter = userIDChinhSua != null ?
                new ObjectParameter("UserIDChinhSua", userIDChinhSua) :
                new ObjectParameter("UserIDChinhSua", typeof(string));
    
            var thoiGianChinhSuaParameter = thoiGianChinhSua.HasValue ?
                new ObjectParameter("ThoiGianChinhSua", thoiGianChinhSua) :
                new ObjectParameter("ThoiGianChinhSua", typeof(System.DateTime));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tblChiTieuBienDong_Insert", maChiTieuBienDong, maChiTieuParameter, maChiTieuChaParameter, kyHieuMoiParameter, tenChiTieuMoiParameter, congZonParameter, thoiGianApDungParameter, thoiGianHetHanParameter, thuTuParameter, userIDKhoiTaoParameter, thoiGianKhoiTaoParameter, userIDChinhSuaParameter, thoiGianChinhSuaParameter, ghiChuParameter);
        }
    
        public virtual ObjectResult<sp_tblChiTieuBienDong_SelectAll_Result> sp_tblChiTieuBienDong_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tblChiTieuBienDong_SelectAll_Result>("sp_tblChiTieuBienDong_SelectAll");
        }
    
        public virtual int sp_tblChiTieuBienDong_SelectByField(string fieldName, string value)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tblChiTieuBienDong_SelectByField", fieldNameParameter, valueParameter);
        }
    
        public virtual ObjectResult<sp_tblChiTieuBienDong_SelectByPrimaryKey_Result> sp_tblChiTieuBienDong_SelectByPrimaryKey(Nullable<long> maChiTieuBienDong)
        {
            var maChiTieuBienDongParameter = maChiTieuBienDong.HasValue ?
                new ObjectParameter("MaChiTieuBienDong", maChiTieuBienDong) :
                new ObjectParameter("MaChiTieuBienDong", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tblChiTieuBienDong_SelectByPrimaryKey_Result>("sp_tblChiTieuBienDong_SelectByPrimaryKey", maChiTieuBienDongParameter);
        }
    
        public virtual int sp_tblChiTieuBienDong_Update(Nullable<long> maChiTieuBienDong, Nullable<long> maChiTieu, Nullable<long> maChiTieuCha, string kyHieuMoi, string tenChiTieuMoi, string congZon, Nullable<System.DateTime> thoiGianApDung, Nullable<System.DateTime> thoiGianHetHan, Nullable<int> thuTu, string userIDKhoiTao, Nullable<System.DateTime> thoiGianKhoiTao, string userIDChinhSua, Nullable<System.DateTime> thoiGianChinhSua, string ghiChu)
        {
            var maChiTieuBienDongParameter = maChiTieuBienDong.HasValue ?
                new ObjectParameter("MaChiTieuBienDong", maChiTieuBienDong) :
                new ObjectParameter("MaChiTieuBienDong", typeof(long));
    
            var maChiTieuParameter = maChiTieu.HasValue ?
                new ObjectParameter("MaChiTieu", maChiTieu) :
                new ObjectParameter("MaChiTieu", typeof(long));
    
            var maChiTieuChaParameter = maChiTieuCha.HasValue ?
                new ObjectParameter("MaChiTieuCha", maChiTieuCha) :
                new ObjectParameter("MaChiTieuCha", typeof(long));
    
            var kyHieuMoiParameter = kyHieuMoi != null ?
                new ObjectParameter("KyHieuMoi", kyHieuMoi) :
                new ObjectParameter("KyHieuMoi", typeof(string));
    
            var tenChiTieuMoiParameter = tenChiTieuMoi != null ?
                new ObjectParameter("TenChiTieuMoi", tenChiTieuMoi) :
                new ObjectParameter("TenChiTieuMoi", typeof(string));
    
            var congZonParameter = congZon != null ?
                new ObjectParameter("CongZon", congZon) :
                new ObjectParameter("CongZon", typeof(string));
    
            var thoiGianApDungParameter = thoiGianApDung.HasValue ?
                new ObjectParameter("ThoiGianApDung", thoiGianApDung) :
                new ObjectParameter("ThoiGianApDung", typeof(System.DateTime));
    
            var thoiGianHetHanParameter = thoiGianHetHan.HasValue ?
                new ObjectParameter("ThoiGianHetHan", thoiGianHetHan) :
                new ObjectParameter("ThoiGianHetHan", typeof(System.DateTime));
    
            var thuTuParameter = thuTu.HasValue ?
                new ObjectParameter("ThuTu", thuTu) :
                new ObjectParameter("ThuTu", typeof(int));
    
            var userIDKhoiTaoParameter = userIDKhoiTao != null ?
                new ObjectParameter("UserIDKhoiTao", userIDKhoiTao) :
                new ObjectParameter("UserIDKhoiTao", typeof(string));
    
            var thoiGianKhoiTaoParameter = thoiGianKhoiTao.HasValue ?
                new ObjectParameter("ThoiGianKhoiTao", thoiGianKhoiTao) :
                new ObjectParameter("ThoiGianKhoiTao", typeof(System.DateTime));
    
            var userIDChinhSuaParameter = userIDChinhSua != null ?
                new ObjectParameter("UserIDChinhSua", userIDChinhSua) :
                new ObjectParameter("UserIDChinhSua", typeof(string));
    
            var thoiGianChinhSuaParameter = thoiGianChinhSua.HasValue ?
                new ObjectParameter("ThoiGianChinhSua", thoiGianChinhSua) :
                new ObjectParameter("ThoiGianChinhSua", typeof(System.DateTime));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tblChiTieuBienDong_Update", maChiTieuBienDongParameter, maChiTieuParameter, maChiTieuChaParameter, kyHieuMoiParameter, tenChiTieuMoiParameter, congZonParameter, thoiGianApDungParameter, thoiGianHetHanParameter, thuTuParameter, userIDKhoiTaoParameter, thoiGianKhoiTaoParameter, userIDChinhSuaParameter, thoiGianChinhSuaParameter, ghiChuParameter);
        }
    
        public virtual int sp_tblSoLieuChiTieu_DeleteByField(string fieldName, string value)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tblSoLieuChiTieu_DeleteByField", fieldNameParameter, valueParameter);
        }
    
        public virtual int sp_tblSoLieuChiTieu_DeleteByPrimaryKey(Nullable<long> maSoLieuChiTieu)
        {
            var maSoLieuChiTieuParameter = maSoLieuChiTieu.HasValue ?
                new ObjectParameter("MaSoLieuChiTieu", maSoLieuChiTieu) :
                new ObjectParameter("MaSoLieuChiTieu", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tblSoLieuChiTieu_DeleteByPrimaryKey", maSoLieuChiTieuParameter);
        }
    
        public virtual int sp_tblSoLieuChiTieu_Insert(ObjectParameter maSoLieuChiTieu, Nullable<long> maChiTieu, string maCuoc, Nullable<System.DateTime> thoiGian, string noiDung, Nullable<decimal> soTien, string userIDKhoiTao, Nullable<System.DateTime> thoiGianKhoiTao, string userIDChinhSua, Nullable<System.DateTime> thoiGianChinhSua, string ghiChu)
        {
            var maChiTieuParameter = maChiTieu.HasValue ?
                new ObjectParameter("MaChiTieu", maChiTieu) :
                new ObjectParameter("MaChiTieu", typeof(long));
    
            var maCuocParameter = maCuoc != null ?
                new ObjectParameter("MaCuoc", maCuoc) :
                new ObjectParameter("MaCuoc", typeof(string));
    
            var thoiGianParameter = thoiGian.HasValue ?
                new ObjectParameter("ThoiGian", thoiGian) :
                new ObjectParameter("ThoiGian", typeof(System.DateTime));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            var soTienParameter = soTien.HasValue ?
                new ObjectParameter("SoTien", soTien) :
                new ObjectParameter("SoTien", typeof(decimal));
    
            var userIDKhoiTaoParameter = userIDKhoiTao != null ?
                new ObjectParameter("UserIDKhoiTao", userIDKhoiTao) :
                new ObjectParameter("UserIDKhoiTao", typeof(string));
    
            var thoiGianKhoiTaoParameter = thoiGianKhoiTao.HasValue ?
                new ObjectParameter("ThoiGianKhoiTao", thoiGianKhoiTao) :
                new ObjectParameter("ThoiGianKhoiTao", typeof(System.DateTime));
    
            var userIDChinhSuaParameter = userIDChinhSua != null ?
                new ObjectParameter("UserIDChinhSua", userIDChinhSua) :
                new ObjectParameter("UserIDChinhSua", typeof(string));
    
            var thoiGianChinhSuaParameter = thoiGianChinhSua.HasValue ?
                new ObjectParameter("ThoiGianChinhSua", thoiGianChinhSua) :
                new ObjectParameter("ThoiGianChinhSua", typeof(System.DateTime));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tblSoLieuChiTieu_Insert", maSoLieuChiTieu, maChiTieuParameter, maCuocParameter, thoiGianParameter, noiDungParameter, soTienParameter, userIDKhoiTaoParameter, thoiGianKhoiTaoParameter, userIDChinhSuaParameter, thoiGianChinhSuaParameter, ghiChuParameter);
        }
    
        public virtual ObjectResult<sp_tblSoLieuChiTieu_SelectAll_Result> sp_tblSoLieuChiTieu_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tblSoLieuChiTieu_SelectAll_Result>("sp_tblSoLieuChiTieu_SelectAll");
        }
    
        public virtual int sp_tblSoLieuChiTieu_SelectByField(string fieldName, string value)
        {
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("FieldName", fieldName) :
                new ObjectParameter("FieldName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tblSoLieuChiTieu_SelectByField", fieldNameParameter, valueParameter);
        }
    
        public virtual ObjectResult<sp_tblSoLieuChiTieu_SelectByPrimaryKey_Result> sp_tblSoLieuChiTieu_SelectByPrimaryKey(Nullable<long> maSoLieuChiTieu)
        {
            var maSoLieuChiTieuParameter = maSoLieuChiTieu.HasValue ?
                new ObjectParameter("MaSoLieuChiTieu", maSoLieuChiTieu) :
                new ObjectParameter("MaSoLieuChiTieu", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tblSoLieuChiTieu_SelectByPrimaryKey_Result>("sp_tblSoLieuChiTieu_SelectByPrimaryKey", maSoLieuChiTieuParameter);
        }
    
        public virtual int sp_tblSoLieuChiTieu_Update(Nullable<long> maSoLieuChiTieu, Nullable<long> maChiTieu, string maCuoc, Nullable<System.DateTime> thoiGian, string noiDung, Nullable<decimal> soTien, string userIDKhoiTao, Nullable<System.DateTime> thoiGianKhoiTao, string userIDChinhSua, Nullable<System.DateTime> thoiGianChinhSua, string ghiChu)
        {
            var maSoLieuChiTieuParameter = maSoLieuChiTieu.HasValue ?
                new ObjectParameter("MaSoLieuChiTieu", maSoLieuChiTieu) :
                new ObjectParameter("MaSoLieuChiTieu", typeof(long));
    
            var maChiTieuParameter = maChiTieu.HasValue ?
                new ObjectParameter("MaChiTieu", maChiTieu) :
                new ObjectParameter("MaChiTieu", typeof(long));
    
            var maCuocParameter = maCuoc != null ?
                new ObjectParameter("MaCuoc", maCuoc) :
                new ObjectParameter("MaCuoc", typeof(string));
    
            var thoiGianParameter = thoiGian.HasValue ?
                new ObjectParameter("ThoiGian", thoiGian) :
                new ObjectParameter("ThoiGian", typeof(System.DateTime));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            var soTienParameter = soTien.HasValue ?
                new ObjectParameter("SoTien", soTien) :
                new ObjectParameter("SoTien", typeof(decimal));
    
            var userIDKhoiTaoParameter = userIDKhoiTao != null ?
                new ObjectParameter("UserIDKhoiTao", userIDKhoiTao) :
                new ObjectParameter("UserIDKhoiTao", typeof(string));
    
            var thoiGianKhoiTaoParameter = thoiGianKhoiTao.HasValue ?
                new ObjectParameter("ThoiGianKhoiTao", thoiGianKhoiTao) :
                new ObjectParameter("ThoiGianKhoiTao", typeof(System.DateTime));
    
            var userIDChinhSuaParameter = userIDChinhSua != null ?
                new ObjectParameter("UserIDChinhSua", userIDChinhSua) :
                new ObjectParameter("UserIDChinhSua", typeof(string));
    
            var thoiGianChinhSuaParameter = thoiGianChinhSua.HasValue ?
                new ObjectParameter("ThoiGianChinhSua", thoiGianChinhSua) :
                new ObjectParameter("ThoiGianChinhSua", typeof(System.DateTime));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tblSoLieuChiTieu_Update", maSoLieuChiTieuParameter, maChiTieuParameter, maCuocParameter, thoiGianParameter, noiDungParameter, soTienParameter, userIDKhoiTaoParameter, thoiGianKhoiTaoParameter, userIDChinhSuaParameter, thoiGianChinhSuaParameter, ghiChuParameter);
        }
    
        public virtual ObjectResult<string> genCode(string namkt, string donvi, string linhvuc, string loaihinh)
        {
            var namktParameter = namkt != null ?
                new ObjectParameter("namkt", namkt) :
                new ObjectParameter("namkt", typeof(string));
    
            var donviParameter = donvi != null ?
                new ObjectParameter("donvi", donvi) :
                new ObjectParameter("donvi", typeof(string));
    
            var linhvucParameter = linhvuc != null ?
                new ObjectParameter("linhvuc", linhvuc) :
                new ObjectParameter("linhvuc", typeof(string));
    
            var loaihinhParameter = loaihinh != null ?
                new ObjectParameter("loaihinh", loaihinh) :
                new ObjectParameter("loaihinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("genCode", namktParameter, donviParameter, linhvucParameter, loaihinhParameter);
        }
    
        public virtual ObjectResult<getTrienKhai_Result> getTrienKhai(string namkt, Nullable<System.DateTime> ngaylapbc, string donvi)
        {
            var namktParameter = namkt != null ?
                new ObjectParameter("namkt", namkt) :
                new ObjectParameter("namkt", typeof(string));
    
            var ngaylapbcParameter = ngaylapbc.HasValue ?
                new ObjectParameter("ngaylapbc", ngaylapbc) :
                new ObjectParameter("ngaylapbc", typeof(System.DateTime));
    
            var donviParameter = donvi != null ?
                new ObjectParameter("donvi", donvi) :
                new ObjectParameter("donvi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getTrienKhai_Result>("getTrienKhai", namktParameter, ngaylapbcParameter, donviParameter);
        }
    
        public virtual ObjectResult<getCuocStatus_thkqkt_Result> getCuocStatus_thkqkt(string namkt, Nullable<System.DateTime> ngaylapbc, string cat, string madonvi)
        {
            var namktParameter = namkt != null ?
                new ObjectParameter("namkt", namkt) :
                new ObjectParameter("namkt", typeof(string));
    
            var ngaylapbcParameter = ngaylapbc.HasValue ?
                new ObjectParameter("ngaylapbc", ngaylapbc) :
                new ObjectParameter("ngaylapbc", typeof(System.DateTime));
    
            var catParameter = cat != null ?
                new ObjectParameter("cat", cat) :
                new ObjectParameter("cat", typeof(string));
    
            var madonviParameter = madonvi != null ?
                new ObjectParameter("madonvi", madonvi) :
                new ObjectParameter("madonvi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getCuocStatus_thkqkt_Result>("getCuocStatus_thkqkt", namktParameter, ngaylapbcParameter, catParameter, madonviParameter);
        }
    
        public virtual ObjectResult<getCuocByID_Result> getCuocByID(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getCuocByID_Result>("getCuocByID", iDParameter);
        }
    
        public virtual ObjectResult<sp_TongHopKetQua_List_Result> sp_TongHopKetQua_List(Nullable<int> maCuoc, Nullable<System.DateTime> ngayThucHien)
        {
            var maCuocParameter = maCuoc.HasValue ?
                new ObjectParameter("MaCuoc", maCuoc) :
                new ObjectParameter("MaCuoc", typeof(int));
    
            var ngayThucHienParameter = ngayThucHien.HasValue ?
                new ObjectParameter("NgayThucHien", ngayThucHien) :
                new ObjectParameter("NgayThucHien", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TongHopKetQua_List_Result>("sp_TongHopKetQua_List", maCuocParameter, ngayThucHienParameter);
        }
    }
}
